import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'

import {selectAuthState, setAuthState} from "../store/authSlice";
import {useDispatch, useSelector} from "react-redux";


const inter = Inter({subsets: ['latin']})

export default function Home() {
    const authState = useSelector(selectAuthState);
    const dispatch = useDispatch();
    return (
        <>
            <Head>
                <title>Book Store Demo</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div className={styles.description}>
                    <p>
                        This is the Book Store Demo by Rui Yang based on NextJs Default Project&nbsp;
                        {/*<code className={styles.code}>pages/index.tsx</code>*/}
                    </p>
                </div>

                <div>
                    <div>
                        <div>{authState ? "Logged in" : "Not Logged In"}</div>
                        <button
                            onClick={() =>{
                                authState
                                    ? dispatch(setAuthState(false))
                                    : dispatch(setAuthState(true))
                            }

                            }
                        >
                            {authState ? "Logout" : "LogIn"}
                        </button>
                    </div>
                </div>
            </main>
        </>
    )
}
